AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/**
    - config/**
    - script/**
    - tmp/**
    - vendor/**
    - deploy/**

LineLength:
  Enabled: true
  Max: 120

StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Documentation:
  Enabled: false

Encoding:
  Enabled: false

Rails:
  Enabled: true

MethodLength:
  Max: 15
