AllCops:
  Includes:
    - Rakefile
    - config.ru
  Excludes:
    - db/**
    - config/**
    - script/**
    - tmp/**
    - vendor/**
    - deploy/**

LineLength:
  Enabled: true
  Max: 120

StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Documentation:
  Enabled: false

Encoding:
  Enabled: false

AllCops:
  RunRailsCops: true

MethodLength:
  Max: 15

ReduceArguments:
  Enabled: false
